namespace CrewBoomMonobehaviours
{
    public enum BrcCharacter
    {
        Vinyl,
        Frank,
        Coil,
        Red,
        Tryce,
        Bel,
        Rave,
        DotExeMember,
        Solace,
        DjCyber,
        EclipseMember,
        DevilTheoryMember,
        FauxWithBoostPack,
        FleshPrince,
        Irene,
        Felix,
        OldHeadMember,
        Base,
        Jet,
        Mesh,
        FuturismMember,
        Rise,
        Shine,
        FauxWithoutBoostPack,
        DotExeBoss,
        FelixWithCyberHead
    }
}
